apiVersion: v1
kind: Secret
metadata:
  name: infisical-creds
type: Opaque
stringData:
  client-id: "PLACEHOLDER_WILL_BE_REPLACED_BY_CICD"
  client-secret: "PLACEHOLDER_WILL_BE_REPLACED_BY_CICD"
  project-id: "PLACEHOLDER_WILL_BE_REPLACED_BY_CICD"
