apiVersion: v1
kind: Secret
metadata:
  name: infisical-creds
type: Opaque
stringData:
  INFISICAL_CLIENT_ID: "PLACEHOLDER_WILL_BE_REPLACED_BY_CICD"
  INFISICAL_CLIENT_SECRET: "PLACEHOLDER_WILL_BE_REPLACED_BY_CICD"
  INFISICAL_PROJECT_ID: "PLACEHOLDER_WILL_BE_REPLACED_BY_CICD"
