<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-WiseWizard.Host-319cdc3d-8cac-415e-8992-368ebeca5ebc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.Core" />
    <PackageReference Include="Hangfire.PostgreSql" />
    <PackageReference Include="Infisical.Sdk" />
    <PackageReference Include="Telegram.Bot" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WiseWizard.Core\WiseWizard.Core.csproj" />
    <ProjectReference Include="..\WiseWizard.Infrastructure\WiseWizard.Infrastructure.csproj" />
    <ProjectReference Include="..\WiseWizard.Bot\WiseWizard.Bot.csproj" />
    <ProjectReference Include="..\Aspire\WiseWizard.ServiceDefaults\WiseWizard.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
